version: 2
jobs:
  build:
    working_directory: /go/src/github.com/flowerinthenight/golang-monorepo
    docker:
    - image: golang:1.9.4
    steps:
    - checkout
    - setup_remote_docker:
        version: 17.11.0-ce
    - run:
        name: build
        shell: /bin/bash
        command: |
          chmod +x ./build-circleci2.0.sh
          ./build-circleci2.0.sh
